### PR TITLE
fix(lgtm): fixes LGTM alerts

### PR DESCRIPTION
**Pull request by diwanshi**
# Fixes
Fixes the alerts from lgtm bot

### 

## Does this PR introduce a breaking change

No

### CODE REVIEW

**Comment by sayak-sarkar** [comment]
@diwanshi can you please update the title of the PR to fix(lgtm): fixes LGTM alerts to follow semantic commit [guidelines](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) ?

**Review by sayak-sarkar — APPROVED** [review]

**Comment by diwanshi** [comment]
@sayak-sarkar yes done

**Comment by hybridx** [comment]
> @sayak-sarkar yes done

@diwanshi These changes are also done here https://github.com/1-Platform/op-components/pull/49 
I suppose we should remove it from there.
@gisumit Can you remove it from https://github.com/1-Platform/op-components/pull/49

**Review by hybridx — APPROVED** [review]
LGTM

**Review by gisumit — APPROVED** [review]
LGTM

**Pull request merged**
