### PR TITLE
feat: changed search style in opc-menu-drawer

### PR DESCRIPTION
**Pull request by akhilmhdh**
# Resolves

# Explain the feature/fix

1. Changed search to top
2. Fixed font issues

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

## Drawer

Screenshot 2021-12-24 at 11 59 53 AM

## Drawer with search

Screenshot 2021-12-24 at 12 00 03 PM

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] My changes generate no new warnings
- [x] I have performed a self-review of my own code
- [x] I have documented my code, particularly in areas like todo, complex logic, quick fix, temporary patch, etc.
#### Browsers you have tested in
- [x] Latest two versions of Mozilla Firefox and Google Chrome supported by Red Hat Enterprise Linux distribution
- [x] Google Chrome [Latest 2 versions]
- [x] Mozilla Firefox [Latest 2 versions]
- [x] Microsoft Edge [Latest 2 versions]
- [ ] Apple Safari [Latest 2 versions]
- [ ] Microsoft Internet Explorer 11

### CODE REVIEW

**Review by hybridx — APPROVED** [review]
LGTM

**Comment by hybridx** [comment]
@akhilmhdh please resolve the merge conflicts

**Comment by akhilmhdh** [comment]
@hybridx can you tell me how to resolve this LGTM error. I just did an npm install again. Seems nothing changed in package-lock.json

**Comment by riginoommen** [comment]
> @hybridx can you tell me how to resolve this LGTM error. I just did an npm install again. Seems nothing changed in package-lock.json

@hybridx rebase with upstream on this branch this branch have conflict

**Comment by akhilmhdh** [comment]
Ahh ok. @riginoommen got it

**Review by deshmukhmayur — APPROVED** [review]

**Pull request merged**
