### PR TITLE
feat(2252): removed explicit pfe dependency on op-feedback

### PR DESCRIPTION
**Pull request by akhilmhdh**
# Closes

1. 2252

# Explain the feature/fix

1. Removed pfe dependency from using op-feedback

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

Screenshot 2022-10-20 at 12 53 46 PM

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] My changes generate no new warnings
- [x] I have performed a self-review of my own code
- [x] I have documented my code, particularly in areas like todo, complex logic, quick fix, temporary patch, etc.
#### If it is a new component
- [x] Does your component follow One Platform style guidelines?
- [x] Does your component web accessibility standards? [Helper Doc](https://www.w3.org/TR/wai-aria-1.1/)
- [x] Does your component support desktop screen sizes (350px, 720px, 1150px ,1920px)
#### Browsers you have tested in
- [ ] Latest two versions of Mozilla Firefox and Google Chrome supported by Red Hat Enterprise Linux distribution
- [x] Google Chrome [Latest 2 versions]
- [x] Mozilla Firefox [Latest 2 versions]
- [ ] Microsoft Edge [Latest 2 versions]
- [ ] Apple Safari [Latest 2 versions]
- [ ] Microsoft Internet Explorer 11

### CODE REVIEW

**Comment by akhilmhdh** [comment]
To reviewers. I have copied the pfe root global variables to host in web component because lit elements expects the variables to be in host rather than root. Then only it works on firefox.

**Comment by hybridx** [comment]
@akhilmhdh does this remove the dependency with patternfly? if so can you add the same changes in the scaffolding as well?

**Comment by hybridx** [comment]
@akhilmhdh can you also check the RH font??

**Review by riginoommen — APPROVED** [review]

**Comment by hybridx** [comment]
@akhilmhdh can you check why the test is failing

**Comment by akhilmhdh** [comment]
@hybridx fixed

**Review by riginoommen — APPROVED** [review]

**Review by hybridx — APPROVED** [review]

**Pull request merged**
