### PR TITLE
feat(1755): added spa name to feedback component

### PR DESCRIPTION
**Pull request by akhilmhdh**
# Closes

1. 1755

# Explain the feature/fix

1. Added application name in feedback component in bug reporting and feedback report
2. Default value is `one platform`  and `/`

## Does this PR introduce a breaking change

No

## Screenshots

<details>
<summary>View Screenshots</summary>

## Theme blue feedback options

Screenshot 2022-02-02 at 10 52 30 AM

## Theme blue bug report

Screenshot 2022-02-02 at 10 52 36 AM

 ## Theme blue feedback report
 
Screenshot 2022-02-02 at 10 52 42 AM

## Theme red feedback options

Screenshot 2022-02-02 at 10 53 17 AM

## Theme red bug report

Screenshot 2022-02-02 at 10 53 22 AM

 ## Theme red feedback report
 
Screenshot 2022-02-02 at 10 53 30 AM

</details>

### Ready-for-merge Checklist

- [x] Expected files: all files in this pull request are related to one feature request or issue (no stragglers)?
- [x] Does the change have appropriate unit tests?
- [x] Did tests pass?
- [x] Did you update or add any necessary documentation (README.md, WHY.md, etc.)?
- [x] My changes generate no new warnings
- [x] I have performed a self-review of my own code
- [x] I have documented my code, particularly in areas like todo, complex logic, quick fix, temporary patch, etc.
#### If it is a new component
- [x] Does your component follow One Platform style guidelines?
- [x] Does your component web accessibility standards? [Helper Doc](https://www.w3.org/TR/wai-aria-1.1/)
- [x] Does your component support desktop screen sizes (350px, 720px, 1150px ,1920px)
#### Browsers you have tested in
- [x] Latest two versions of Mozilla Firefox and Google Chrome supported by Red Hat Enterprise Linux distribution
- [x] Google Chrome [Latest 2 versions]
- [x] Mozilla Firefox [Latest 2 versions]
- [x] Microsoft Edge [Latest 2 versions]
- [x] Apple Safari [Latest 2 versions]
- [x] Microsoft Internet Explorer 11

### CODE REVIEW

**Comment by hybridx** [comment]
@akhilmhdh can you check the error on test and also the code scanning results

**Comment by akhilmhdh** [comment]
@hybridx Codeql is not based on this one. It has been the one used before the regex one.

Test is also same. It's a design issue, the contrast difference. I think @gisumit needs to look into this

**Comment by hybridx** [comment]
@akhilmhdh It's an aria error can and same with CI, not sure why it didn't report if it was added before. For now can you try to fix it? 
Because without fixing both of them we cannot merge this PR

**Comment by akhilmhdh** [comment]
Screenshot 2022-02-02 at 2 11 32 PM

@hybridx  Fixed both the issues. @gisumit  I had to increase the contrast difference between foreground and background for red theme to avoid axe violation. Check it out.

**Comment by akhilmhdh** [comment]
The above is old one. Check the PR status LGTM

**Review by ghanlohar — APPROVED** [review]

**Comment by akhilmhdh** [comment]
@hybridx @gisumit kindly look into this now

**Review by riginoommen — APPROVED** [review]

**Review by hybridx — APPROVED** [review]

**Comment by hybridx** [comment]
@gisumit can you please review and merge

cc @akhilmhdh

**Review by gisumit — APPROVED** [review]

**Pull request merged**
